blank_issues_enabled: false
contact_links:
  - name: "0G Studio Survey (App Suite)"
    url: https://forms.gle/ymEdZrdTNs4giEm1A
    about: "Required L0 Recruit survey. No bug report is required for Recruit."
  - name: "0G Private Computer Survey"
    url: https://forms.gle/G919xrbRyfVJxPZe8
    about: "Required L0 Recruit survey. No bug report is required for Recruit."
